version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./DB/.env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3000
    env_file:
      - ./DB/.env
    volumes:
      - ./backend:/app
      - backend-modules:/app/node_modules
    networks:
      - todo
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3000
    volumes:
      - ./frontend:/app
      - frontend-modules:/app/node_modules
    networks:
      - todo
    depends_on:
      - backend
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./nginx/logs:/var/log/nginx
    ports:
      - '80:80'
    networks:
      - todo
    depends_on:
      - backend
      - frontend

networks:
  todo:
    driver: bridge

volumes:
  mysql-data:
  frontend-modules:
  backend-modules:
